name: update docker image

on:
  push:
    branches: [ dev, master ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set docker image tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "IMAGE_TAG=dev" >> "$GITHUB_ENV"
            echo "CREATE_IMAGE=true" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "IMAGE_TAG=${{ github.ref_name }}" >> "$GITHUB_ENV"
            echo "CREATE_IMAGE=true" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "IMAGE_TAG=latest" >> "$GITHUB_ENV"
            echo "CREATE_IMAGE=true" >> "$GITHUB_ENV"
          else
            echo "CREATE_IMAGE=false" >> "$GITHUB_ENV"
          fi

      - name: Login to Docker Hub
        if: env.CREATE_IMAGE == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: env.CREATE_IMAGE == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: env.CREATE_IMAGE == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }}
